# COMP S493F Lab 1

In this lesson, you'll work on:

- essential operations of using Google Colab,
- Python collections and comprehension, and
- NumPy basics.

### Student name: *LO TSZ KIN*


# Using Google Colab

If necessary, refer to Lab 0 for the basics of using Google Colab and a reference of selected Markdown syntax.

# Practice - Question 1 of 3

For all code cells in this and other questions, run the cells after modification and include the outputs in the notebook unless instructed otherwise. Create code cells and text cells as necessary.

## Q1a

Write Python code in the following cell to print your name.

In [ ]:

print("LO TSZ KIN")


LO TSZ KIN


## Q1b

Create a code cell below to run the three shell commands: `pwd`, `free -h`, and `df -h`. Remember to write the exclamation mark `!` at the beginning of each command.  (Note that the outputs contain memory and storage information of the Colab virtual machine you're using.)

In [ ]:
!pwd
!free -h
!df -h
!ls

/content
               total        used        free      shared  buff/cache   available
Mem:            12Gi       747Mi       8.9Gi       1.0Mi       3.0Gi        11Gi
Swap:             0B          0B          0B
Filesystem      Size  Used Avail Use% Mounted on
overlay         108G   27G   82G  25% /
tmpfs            64M     0   64M   0% /dev
shm             5.8G     0  5.8G   0% /dev/shm
/dev/root       2.0G  1.1G  849M  57% /usr/sbin/docker-init
tmpfs           6.4G  304K  6.4G   1% /var/colab
/dev/sda1        71G   54G   17G  77% /etc/hosts
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware
sample_data


## Q1c

Create a text cell below to write a Markdown list of 3 (or more) items. The items are courses you have taken and related to programming or machine learning or data science.

Solution:


<div class='alert alert-warning' role='alert'><b>COMP S493F , COMP S416F , COMP S381F</b></div>




## Q1d

Create a text cell below to write a Markdown table of 2 columns and 3 (or more) rows. Specify the column headers as `Programming language` and `Familiarity (1-5)`. Fill in the rows with 3 (or more) programming languages you know and your familiarity with them (1 for lowest familiarity and 5 for highest familiarity).

Solution:

Programning language | Familiarity (1-5)
-:|-
C++ | 2
Python | 2
Jave |2
SQL | 3




## &#x2766;

# Python collections

In Python, some commonly-used collections types are lists, tuples, sets, and dictionaries.

## Lists and tuples

A *list* is a sequence, or an ordered collection, of items. The `len()` function returns the number of items in a list.

In [ ]:
ls = [1, 2.0, "three"]
print(ls)
print(type(ls))
print(len(ls))

[1, 2.0, 'three']
<class 'list'>
3


An individual item in a list can be accessed by integer indexing, with syntax `a_list[index]`. Note the f-string syntax: `f"{exp}"` displays the value of `exp`; `f"{exp=}"` displays the expression `exp`, an equal symbol, and the value of `exp` -- very useful for debugging and exploring code!

In [ ]:
print(ls)
print(f"{ls[0]=}, {ls[1]=}")  # index is 0-based; index 0 -> first item
print(f"{ls[2]=}, {ls[-1]=}")  # index -1 -> last item

[1, 2.0, 'three']
ls[0]=1, ls[1]=2.0
ls[2]='three', ls[-1]='three'


Multiple items in a list can be accessed by slicing, with syntax `a_list[start:stop:step]`. Note that the item at the `stop` index is excluded.

In [ ]:
ls = [0, 1, 2, 3, 4, 5, 6]
print(ls)
print(f"{ls[2:6] = }")  # from index 2 (included) to index 6 (excluded)
print(f"{ls[:6] = }")  # start index 0 by default here
print(f"{ls[2:] = }")  # stop index len+1 (=7) by default here
print(f"{ls[:] = }")  # all items, i.e. making a copy
print(f"{ls[::2] = }")  # steps of 2, i.e. every other items
print(f"{ls[::-1] = }") # all items in reversed order

[0, 1, 2, 3, 4, 5, 6]
ls[2:6] = [2, 3, 4, 5]
ls[:6] = [0, 1, 2, 3, 4, 5]
ls[2:] = [2, 3, 4, 5, 6]
ls[:] = [0, 1, 2, 3, 4, 5, 6]
ls[::2] = [0, 2, 4, 6]
ls[::-1] = [6, 5, 4, 3, 2, 1, 0]


Lists are *mutable*, meaning that their contents may be changed during code execution.

In [ ]:
ls = [1, 2, 3]
print(ls)
ls[0] = 10  # modify the 1st item, i.e. with index 0
print(ls)
ls.append(40)  # append item at the end
print(ls)

[1, 2, 3]
[10, 2, 3]
[10, 2, 3, 40]


A *tuple* is similar to a list, but *immutable*. That is, once created you cannot modify the contents of a tuple. A tuple has no `append()` method and so on.

In [ ]:
t = (1, 2.0, "three")
print(t)
print(type(t))
# t.append(40)  # no such method!

(1, 2.0, 'three')
<class 'tuple'>


Tuples can be used to create, or assign values to, multiple variables.

In [ ]:
import math  # import the math module
a, b = math.pi, math.e  # two math constants
print(f"{a=:.4f}, {b=:.4f}")  # :.4f for 4 decimal places
a, b = b, a  # swap their values
print(f"{a=:.4f}, {b=:.4f}")  # :.4f for 4 decimal places

a=3.1416, b=2.7183
a=2.7183, b=3.1416


A function can return multiple values in a tuple, e.g. the builtin `divmod()` returns the quotient and remainder of division.

In [ ]:
q, r = divmod(10, 3)
print(q, r)

3 1


## Ranges

A *range* generates a sequence of consecutive, or equally-spaced, integers. It is often used with the `for` loop. The syntax is `range(start, stop, step)`, where `start` and `step` are optional. The meanings of the three parts are similar to those of list slicing syntax `a_list[start:stop:step]`. Again, note that the item of `stop` is excluded.

In [ ]:
for i in range(10):  # from 0 (included) to 10 (excluded)
    print(i, end=" ")  # print " " instead of "\n" at the end

0 1 2 3 4 5 6 7 8 9 

In [ ]:
for i in range(5, 10):  # from 5 (included) to 10 (excluded)
    print(i, end=" ")

5 6 7 8 9 

In [ ]:
for i in range(5, 10, 2):  # in steps of 2
    print(i, end=" ")

5 7 9 

## Comprehension

*List comprehension* is a "Pythonic" way of generating a new list from an existing sequence of items. The basic syntax is shown below, where `if condition` is optional:

```python
[expr_using_item for item in sequence_of_items if condition]
```

Consider generating the squares of the numbers in an existing list. This can be done using a new list for storing the result and a `for` loop.

In [ ]:
ls = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  # an existing sequence
squares = []  # for keeping result
for item in ls:
    squares.append(item * item)  # put to result
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


Using a list comprehension, the code is more concise and probably easier to read.

In [ ]:
ls = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]  # an existing sequence
squares = [item * item for item in ls]
print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


A range can be used as the existing sequence of items.

In [ ]:
print([n * n for n in range(10)])

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


An optional `if` clause can be added to select items in the existing sequence based on a condition. For example, the squares of only odd numbers (i.e. `n % 2 == 1` is true when `n` is odd) are obtained as follows.

In [ ]:
print([n * n for n in range(10) if n % 2 == 1])

[1, 9, 25, 49, 81]


# Practice - Question 2 of 3

## Q2a

Lists can be nested; that is, a list can contain another list as an item. The following list `ls` contains three nested lists. Note that the lists may have different lengths. Multiple indexing operations may be used to access items in the nested lists. For example, `ls[0]` refers to the first (index 0) nested list, i.e. `[1, 2, 3, 4]`; `ls[0][2]` refers to the third (index 2) item in the nested list `ls[0]`, i.e. `3`.

In [ ]:
ls = [
    [1, 2, 3, 4],
    [5, 6],
    [7, 8, 9, 10]
]
print(ls[0][2])

3


Write code to print the value `6` in `ls` using two positive indices; i.e. write a statement like `print(ls[0][2])` but replace the indices `0` and `2` with other positive indices to display the value `6`.

Write code to print the value `6` in `ls` using two negative indices; i.e. write a statement like `print(ls[0][2])` but replace the indices `0` and `2` with two negative indices to display the value `6`.

In [ ]:
print(ls[1][1])
print(ls[-2][-1])

6
6


## Q2b

Write 4 lines of code to do the following:

- Create a list of integers from 0 to 9, with code `ls = list(range(10))`.
- Using `print()`, `ls`, and slicing, print the slice result `[6, 7, 8, 9]`.
- Using `print()`, `ls`, and slicing, print the slice result `[3, 6, 9]`.
- Using `print()`, `ls`, and slicing, print the slice result `[9, 5, 1]`.

In [ ]:

ls = list(range(10))

print(ls[6:])
print(ls[3::3])
print(ls[::-4])


[6, 7, 8, 9]
[3, 6, 9]
[9, 5, 1]


## Q2c

The following `is_prime(n)` function returns `True` if `n` is a prime number or `False` otherwise. Using this function and a list comprehension, write code to print the list of prime numbers between 2 and 200, i.e. `[2, 3, 5, 7, ... 199]`. Hint: in a list comprehension, the expression using the item may be just the item, i.e. `[n for n in ...]`.

In [ ]:
def is_prime(n):
    for i in range(2, int(n ** 0.5 + 1)):
        if n % i == 0:
            return False
    return True


# ===== =====> Replace this line by your code. <===== ===== #
prime_numbers = [n for n in range(2,201)if is_prime(n)]

print(prime_numbers)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199]


## &#x2766;

# NumPy basics

The NumPy library implements efficient multi-dimensional arrays and related operations. It is heavily used in machine learning libraries such as Scikit-learn and TensorFlow.

## Array creation and properties

By convention, NumPy is often imported as the name `np`. A NumPy array can be created using the `np.array()` function.

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


The following code examines various properties of an array.

In [ ]:
print(f"{arr.size=}")  # number of items in array
print(f"{arr.shape=}")  # dimensions of array
print(f"{arr.ndim=}")  # number of dimensions, 1D or 2D etc
print(f"{arr.dtype=}")  # data type of items
print(f"{arr.itemsize=}")  # byte size of an item

arr.size=6
arr.shape=(2, 3)
arr.ndim=2
arr.dtype=dtype('int64')
arr.itemsize=8


In NumPy, a dimension is often called an *axis*; e.g. axis-0 means the first or most dominant dimension of an array.

We can change the dimensions, or shape, of an array using the `reshape()` method or function. Specifying `-1` as a dimension lets NumPy calculate that dimension according to the number of items in the array. `reshape()` would not modify the provided array but return a new array.

In [ ]:
arr2 = arr.reshape((3, -1))  # -1 becomes 6/3=2
print(arr2, arr2.shape)
print(arr, arr.shape)  # arr is not changed!

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2 3]
 [4 5 6]] (2, 3)


In [ ]:
arr3 = np.reshape(arr, (6, 1))  # 2D array of 6x1 items
print(arr3, arr3.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)


In [ ]:
arr4 = np.reshape(arr, (6,))  # 1D array of 6 items
print(arr4, arr4.shape)

[1 2 3 4 5 6] (6,)


## More ways of creating arrays

There are many other ways of creating NumPy arrays. Some are shown below.

In [ ]:
a = np.zeros((2, 5)) # 2D array of 2x5 zeros
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
a = np.ones(5) # 1D array of 5 ones, same as np.ones((5,))
a  # Colab automatically displays the last expression in a code cell

array([1., 1., 1., 1., 1.])

In [ ]:
# No need to keep the array for later use; let's just display it
np.arange(0, 5, 0.5)  # 0 (included) to 5 (excluded) in steps of 0.5

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.linspace(0, 5, 10)  # 10 items from 0 to 5 (both included!)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Array indexing

An item in an array can be accessed using indexing, with index values specified for the dimensions separated by commas, as `arr[r_index, c_index]` for a 2D array.

In [ ]:
a = np.arange(12).reshape((3, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1, 2]  # index 1 -> second row, index 2 -> third column

6

A row is accessed using `arr[r_index]`, while a column using `arr[:, c_index]`. You may think of `:` to mean "all items" in a dimension or along an axis.

In [ ]:
a[1]  # index 1 -> second row, all columns; same as a[1, :]

array([4, 5, 6, 7])

In [ ]:
a[:, 2]  # : -> all rows; index 2 -> third column

array([ 2,  6, 10])

Multiple consecutive columns of an array can be accessed using a slice, i.e. `start:stop:step`, as the column index. The code below accesses the region of all rows and the second and third columns in the array.

In [ ]:
a[:, 1:3]  # : -> all rows, slice 1:3 -> second & third columns

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

# Practice - Question 3 of 3

## Q3a

Write code to do the following:

- Import NumPy as the name `np`.
- Create a 2D array of 5x2 items from 20 (included) to 30 (excluded). Use the `np.arange()` function and the `reshape()` method. Keep it in a variable called `arr`.
- Write `arr` in the last line of the code cell so that it is displayed in execution.

In [ ]:
import numpy as np
X = np.arange(20, 30).reshape(5, 2)
X

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

## Q3b

This part continues to use the `arr` variable above. Write code to display each of the following using `print()`, `arr` and array indexing:

- The value `22` in the array.
- The value `25` in the array.
- The first row, i.e. `[20, 21]`.
- The last column, i.e. `[21, 23, 25, 27, 29]`.
- The last two rows, i.e. `[[26, 27], [28, 29]]`.

In [ ]:
print("The value 22 in the array:", arr[1, 0])
print("The value 25 in the array:", arr[1, 2])
print("The first row:", arr[0])
print("The last column:", arr[:, 1])
print("The last two rows:", arr[3:])

The value 22 in the array: 4
The value 25 in the array: 6
The first row: [1 2 3]
The last column: [2 5]
The last two rows: []


## Q3c

Write code to do the following with proper NumPy API:

- Create an array of 1001 numbers from 100 (included) to 200 (included), using the `np.linspace()` function. Keep the array in a variable called `xs`.
- Display the array `xs`. It should be like `[100. 100.1 100.2 ... 200.]`.
- Display the first 10 items of `xs`.
- Display the last 10 items of `xs`. Hint: use the indexing `[-10:]`.
- Display the number of items in `xs`.

In [ ]:
import numpy as np

xs = np.linspace(100, 200, 1001)

print("Array xs:", xs)
print("First 10 items of xs:", xs[:10])
print("Last 10 items of xs:", xs[-10:])
print("Number of items in xs:", xs.size)



Array xs: [100.  100.1 100.2 ... 199.8 199.9 200. ]
First 10 items of xs: [100.  100.1 100.2 100.3 100.4 100.5 100.6 100.7 100.8 100.9]
Last 10 items of xs: [199.1 199.2 199.3 199.4 199.5 199.6 199.7 199.8 199.9 200. ]
Number of items in xs: 1001


## &#x2766;

# Extras

## More list operations

Items can be removed from a list using the `del` operator or the `pop()` method.

In [ ]:
ls = [1, 2, 3, 4, 5]
print(ls)
del ls[1]  # remove the 2nd item, i.e. with index 1
print(ls)
ls.pop()  # remove item at the end
print(ls)

[1, 2, 3, 4, 5]
[1, 3, 4, 5]
[1, 3, 4]


Some list functions modify list contents in-place (e.g. `extend()`); usually the return values of such functions are not used. Other functions and operations return copies or new lists (e.g. `+`), which are typically assigned to variables for later uses.

In [ ]:
ls = [1, 2, 3]
print(ls)
ls.extend([40, 50])  # add two items in-place
print(ls)  # ls is modified!

[1, 2, 3]
[1, 2, 3, 40, 50]


In [ ]:
ls = [1, 2, 3]
print(ls)
ls2 = ls + [40, 50]  # add two items and put result to ls2
print(ls)  # ls is not modified!
print(ls2)  # result is in ls2

[1, 2, 3]
[1, 2, 3]
[1, 2, 3, 40, 50]


## Sets and dictionaries

A *set* is an unordered collection of unique items. If an item already exists in a set, adding another item of an equal value has no effect.

In [ ]:
s = {1, 2, "three", 1, 2.0, 1, 1}  # equal item skipped
print(s)
print(type(s))
print(len(s))

{'three', 1, 2}
<class 'set'>
3


Use the `add()` method to add an item to a set, and the `in` operator to check if an item exists in a set.

In [ ]:
s = {1, 2, 3}
print(40 in s)
s.add(40)
print(40 in s)

False
True


A *dictionary* is a collection of key-value pairs with unique keys.

In [ ]:
d = {"one": 1, "two": 2, "three": 3, "two": 2.0}  # equal key overriding item
print(d)
print(type(d))
print(len(d))

{'one': 1, 'two': 2.0, 'three': 3}
<class 'dict'>
3


Values in a dictionary can be accessed or added by indexing with the keys. Use the `in` operator to check if a key exists.

In [ ]:
print(d["one"])
print("four" in d)
d["four"] = 4  # add an item as the key doesn't exist
print("four" in d, d["four"])

1
False
True 4


### E1a

For each of the following expressions, write a statement to print the value of the expression, and the type of the value. For example, for an expression `set()`, the statement is `print(set(), type( set() ))`.

- `{}`
- `()`
- `(42)`
- `(42,)`

## NumPy operations along axes

Some NumPy operations can be applied to the whole array or along a certain axis of the array. E.g. in a 2D array, along axis-0 means across the rows downwards, while along axis-1 means across the columns towards the right.

The following code use `max()` to display the maximum value of an array, the maximum value of every column (along axis-0 or across rows downwards), and the maximum value of every row (along axis-1 or across columns towards the right). Note that the array contents are shuffled for more observable results.

In [ ]:
import numpy as np
arr = np.arange(12)
np.random.seed(42)  # reproducible random results
np.random.shuffle(arr)  # shuffle in-place, i.e. modify arr
arr = arr.reshape((3, 4))
print(arr)
print(f"{arr.max() = }")  # max of whole array; same as np.max(arr)
print(f"{arr.max(axis=0) = }")  # max of every column; np.max(arr, axis=0)
print(f"{arr.max(axis=1) = }")  # max of every row; np.max(arr, axis=1)

[[10  9  0  8]
 [ 5  2  1 11]
 [ 4  7  3  6]]
arr.max() = 11
arr.max(axis=0) = array([10,  9,  3, 11])
arr.max(axis=1) = array([10, 11,  7])


### E1b

Write code to create a 2D array of 3x3 integers from 0 (included) to 9 (excluded) in a random order (i.e. with contents shuffle). Display the array, the mean of the whole array, the mean of every column (along axis-0), the mean of every row (along axis-1); use the `np.mean(arr, axis=n)` function.

## Solutions to extra exercises

### E1a

In [ ]:
# Solution
print({}, type({}))
print((), type(()))
print((42), type((42)))
print((42,), type((42,)))

{} <class 'dict'>
() <class 'tuple'>
42 <class 'int'>
(42,) <class 'tuple'>


### E1b

In [ ]:
# Solution
import numpy as np
arr = np.arange(9)
np.random.seed(42)  # reproducible random results
np.random.shuffle(arr)  # shuffle in-place, i.e. modify arr
arr = arr.reshape((3, 3))
print(arr)
print(f"{np.mean(arr) = }")  # mean of whole array; same as arr.mean()
print(f"{np.mean(arr, axis=0) = }")  # mean of every column; arr.mean(axis=0)
print(f"{np.mean(arr, axis=1) = }")  # mean of every row; arr.mean(axis=1)

[[7 1 5]
 [0 8 2]
 [4 3 6]]
np.mean(arr) = 4.0
np.mean(arr, axis=0) = array([3.66666667, 4.        , 4.33333333])
np.mean(arr, axis=1) = array([4.33333333, 3.33333333, 4.33333333])


## &#x2766;